[package]
name = "rust-lib"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.100"
plotter = { git = "https://github.com/Hixos/rust-data-inspector.git" }

[build-dependencies]
cxx-build = "1.0"